name: publish

on:
  push:
    tags:
      - publish.*

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      # npmに公開する.npmrcファイルをセットアップ
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm install -g firebase-tools
      - run: firebase setup:emulators:firestore
      - run: npm run emu:start:firestore &
      - name: エミュレータの起動待機...
        run: sleep 5
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
